
services:
  postgres:
    image: postgres:16
    container_name: domy-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-domy}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-domy}
      POSTGRES_DB: ${DATABASE_NAME:-domy}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
